version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongo
  service:
    build:
      context: .
    depends_on:
      - mongo

volumes:
  mongodata: