name: DeployBE

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: npm install

      # - name: Test
      #   run: npm run test

      # - name: Build
      #   run: npm run build

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Deployment
        id: deployment
        run: |
          aws deploy create-deployment \
            --application-name CD \
            --deployment-group-name DeployBE \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --file-exists-behavior OVERWRITE
